### ISSUE TITLE
 301 Moved Permanently, Location: https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

### ISSUE THREAD

**Issue by spirau** [pH-7/eu-vat-validator#10]
Services has moved to https, please update the source code to reflect it, else the calls are rejected

**Comment by pH-7** [comment]
Patch already available here: https://github.com/pH-7/eu-vat-validator/commit/67c060ee07a753e97eed34b54246d658d1a65332

I will release the v3.0 by now 🙂

**Comment by pH-7** [comment]
@spirau Version now released https://github.com/pH-7/eu-vat-validator/releases/tag/3.0 and available also on Packagist 🙂

Let me know if you have any further issues. Thanks again for reporting this concern 😊

**Comment by pH-7** [comment]
@spirau v3.0 has now been released https://github.com/pH-7/eu-vat-validator/releases/tag/3.0 and available also on Packagist (https://packagist.org/packages/ph-7/eu-vat-validator) 🙂

@spirau Let me know if you have any further issues. Thanks again for reporting this concern 😊

Have a great day! 🚀
