### ISSUE TITLE
Impossible to retrieve the VAT details: MS_UNAVAILABLE

### ISSUE THREAD

**Issue by stefaniehybrid** [pH-7/eu-vat-validator#12]
Previously the VAT validator was working just fine. 
But now I get following error, see screenshot. 
I saw that your code did change a little bit but more in syntax than new code.
So I'm not sure what's not working anymore?
![Scherm­afbeelding 2024-03-15 om 14 49 10](https://github.com/pH-7/eu-vat-validator/assets/143717216/432662f5-f7fa-4ffe-94b1-ac04d5f98087)

**Comment by pH-7** [comment]
Hi @stefaniehybrid,

Thank you very much for raising this issue. It looked like the VAT Europe was temporarily unavailable - https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

Would you mind trying again and confirming if it now works again for you?

**Comment by stefaniehybrid** [comment]
Hi,

This is indeed working again.
Is there a way to have a fallback when the service is down again.
Because now I use this one on my form: https://maes.houston-1.hybridmedia.be/
And it still checked the VAT number but got an error because it couldn’t shown the data behind the VAT number, because the service was down.
Is there a way we just can let it go through but with empty fields and like an error that the service is down?

Greetings

Stefanie Smet
WordPress Developer

M: +32 (0)495 93 55 34
A: Mechelsesteenweg 203 - 2018 Antwerpen
W: hybridagency.be E: ***@***.***
