### ISSUE TITLE
Remove starting / ending comma for getAddress()

### ISSUE THREAD

**Issue by Noaber** [pH-7/eu-vat-validator#2]
When requesting the address, it's starting / ending with a comma.
Probably the $this->oResponse->address starts with a newline

Maybe add a trim or something in the removeNewLines

`return trim(str_replace(["\n", "\r\n"], ', ', $sString), ', ');`

**Comment by pH-7** [comment]
Thanks for the suggestion @Noaber!

Do you might to create a PR doing that? And run the phpunit test (update the test if necessary) once done

Probably, it will be better to create a new method or rename the existing method to something different like `cleanAddress()`

Thanks

**Comment by pH-7** [comment]
BTW @Noaber What's the VAT number you used where you got commas?, so I can reproduce it (because in my case, I don't get commas).

**Comment by pH-7** [comment]
Hi again @Noaber 
How was your vacation?  Did you have the chance to see with what  VAT number you've seen the commas in the address?

**Comment by pH-7** [comment]
👍 Beautiful! Thx!

**Comment by pH-7** [comment]
Thanks @Noaber!
I can see it doesn't normally have commas, as officially shown at http://ec.europa.eu/taxation_customs/vies/
I will publish a patch for it.
