### ISSUE TITLE
The Constructor should throw the exception

### ISSUE THREAD

**Issue by hkwak** [pH-7/eu-vat-validator#3]
https://github.com/pH-7/eu-vat-validator/blob/7f7b5517e95c83be532b0c27fef13836a090b5ef/src/Vat/Provider/Europa.php#L29

The Constructor should throw the exception (kind of ConnectionNotEstablishedException or ProviderNotAvailableException) not just exit, to allow the outer code to deal with the problem (eg display the error message, retry after some delay, etc)

**Comment by pH-7** [comment]
Fixed in https://github.com/pH-7/eu-vat-validator/pull/7
