### ISSUE TITLE
the throws  annotation seems to be redundant

### ISSUE THREAD

**Issue by hkwak** [pH-7/eu-vat-validator#4]
https://github.com/pH-7/eu-vat-validator/blob/7f7b5517e95c83be532b0c27fef13836a090b5ef/src/Vat/Provider/Europa.php#L46

It looks like this getResource method will never throw SoapFault ( which is very good ) because it will be caught in line 57. In only throws the 'Exception' exception, so this annotation can be removed

**Comment by pH-7** [comment]
Fixed in https://github.com/pH-7/eu-vat-validator/pull/5
