### ISSUE TITLE
Unreachable statement

### ISSUE THREAD

**Issue by hkwak** [pH-7/eu-vat-validator#6]
https://github.com/pH-7/eu-vat-validator/blob/7f7b5517e95c83be532b0c27fef13836a090b5ef/src/Vat/Provider/Europa.php#L61

This return will never happen as the exception is thrown in line 59

**Comment by pH-7** [comment]
Good catch! 💯 Do you mind to create a PR for it?

**Comment by hkwak** [comment]
Sure

**Comment by pH-7** [comment]
Fixed https://github.com/pH-7/eu-vat-validator/pull/8
